#NAME ,CONTACT ,CLASS ,SECTION ,EMAIL ,YEAR

print("********************STUDENT BASIC IMFORMATION*****************\n\n")
print("NAME         :  NAYAN REVNATH DESHBHRATAR\n")
print("CONTACT_NO.  :  8625******\n")
print("EMAIL        :  nayandeshbhratar2002@gmail.com\n")
print("CLASS        :  4th SEM \n")
print("SECTION      :  B \n")
print("YEAR         :  2nd YEAR\n")

print("********************STUDENT BIO DATA*****************\n\n")

print("\n-----------------------------------------------------\n")
print("Skills        : \n")
print("--------------------------------------------------------\n")
print("[01] C-Programming\n")
print("[02] C++ Programming\n")
print("[03] Python Programming\n")
print("[04] Adobe Photoshop \n")
print("[05] Adobe Illustrator\n")
print("[06] Git And Github\n")

print("\n--------------------------------------------------------------------------------------------------------------------")
print("PROJECTS AND DEVELOPMENTS     : \n")
print("---------------------------------------------------------------------------------------------------------------------\n")
print('[+] Project              |                     [+]Description                             |    [+]Duration   \n  ')
print("---------------------------------------------------------------------------------------------------------------------\n")
print('(YOUR PROJECT NAME)       |              (YOUR PROJECT DESCRIPTION)             |       (DURATION) \n')
print('(YOUR PROJECT NAME)       |              (YOUR PROJECT DESCRIPTION)             |       (DURATION)   \n')
print('(YOUR PROJECT NAME)       |              (YOUR PROJECT DESCRIPTION)             |       (DURATION)\n')
print('(YOUR PROJECT NAME)       |              (YOUR PROJECT DESCRIPTION)             |       (DURATION)\n')
print('(YOUR PROJECT NAME)       |              (YOUR PROJECT DESCRIPTION)             |       (DURATION)\n')
print('(YOUR PROJECT NAME)       |              (YOUR PROJECT DESCRIPTION)             |       (DURATION)\n')
print('(YOUR PROJECT NAME)       |              (YOUR PROJECT DESCRIPTION)             |       (DURATION) \n')