#TAKING WEIGHT FROM END USER IN KG AND CONVERT IT INTO POUNDS

weight = float(input("ENTER YOUR WEIGHT IN KG : \n"))
pound = float(weight * 2.2)

#PRINTING THE WEIGHT IN POUNDS
print("YOUR WEIGHT IN POUNDS : ",pound)